
modLoader = "javafml"

loaderVersion = "${loader_version_range}"

license = "MIT License"

[[mods]]

modId = "immortalers_delight"

version = "1.20.1-1.0.1"

displayName = "Immortalers Deligh"

authors = "Komeiji_Hako,Renyigesai,babel491734"

description = '''${mod_description}'''

logoFile = "logo.png"

[[dependencies."immortalers_delight"]]

modId = "forge"

mandatory = true

versionRange = "${forge_version_range}"

ordering = "NONE"

side = "BOTH"
[[dependencies."immortalers_delight"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
