
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT License"

[[mods]]
modId = "immortalers_delight"
version = "${mod_version}"
displayName = "Immortalers Deligh"
authors="Komeiji_Hako,Renyigesai,babel491734,ShangguanXi"
description = '''${mod_description}'''
logoFile = "logo.png"

[[dependencies."immortalers_delight"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."immortalers_delight"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
